import {explain} from './engine.js';
const $=id=>document.getElementById(id), pct=v=>`${(100*v).toFixed(1)}%`;
const labels={age:'Age',job:'Job',marital:'Marital status',education:'Education',default:'Credit in default',balance:'Annual balance (€)',housing:'Housing loan',loan:'Personal loan',contact:'Contact channel',day:'Scheduled contact day',month:'Scheduled contact month',campaign:'Contact number in campaign',pdays:'Days since prior contact (−1 = none)',previous:'Previous campaign contacts',poutcome:'Previous campaign outcome'};
const label=k=>labels[k]||k;
function bars(target,items,max=1){$(target).replaceChildren();for(const [key,value] of items){const row=document.createElement('div');row.className='bar-row';const line=document.createElement('div');line.className='bar-label';const name=document.createElement('span');name.textContent=label(key);const number=document.createElement('span');number.textContent=target==='contributions'?`${value>=0?'+':''}${(value*100).toFixed(1)} pp`:pct(value);line.append(name,number);const track=document.createElement('div');track.className='bar-track';const bar=document.createElement('div');bar.className=`bar-fill ${value>=0?'positive':'negative'}`;bar.style.width=`${Math.min(100,Math.abs(value)/max*100)}%`;track.append(bar);row.append(line,track);$(target).append(row);}}
try{
 const response=await fetch('model.json');if(!response.ok)throw new Error('Model unavailable');const model=await response.json();
 const controls={};for(const field of model.schema){const wrapper=document.createElement('label');wrapper.textContent=label(field.name);const control=document.createElement(field.options?'select':'input');control.name=field.name;control.required=true;if(field.options)for(const option of field.options)control.add(new Option(option,option));else{control.type='number';control.min=field.min;control.max=field.max;control.step=1;}control.value=field.default;controls[field.name]=control;wrapper.append(control);$('fields').append(wrapper);}
 function read(){return Object.fromEntries(model.schema.map(f=>[f.name,f.options?controls[f.name].value:Number(controls[f.name].value)]));}
 function render(){const input=read(),result=explain(model,input),yes=result.probability>.5;$('decision').textContent=yes?'Likely to subscribe':'Unlikely to subscribe';$('score').textContent=pct(result.probability);$('score-label').textContent=`Subscription model score · 50% decision threshold${model.weighted?' · class-weighted':''}`;$('meter').style.width=pct(result.probability);const items=Object.entries(result.contributions).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));const supporting=items.filter(([,v])=>yes?v>0:v<0).slice(0,2);$('sentence').textContent=`The model predicts this customer will ${yes?'':'not '}subscribe. `+(supporting.length?`${supporting.map(([k])=>`${label(k)} = ${input[k]}`).join(' and ')} ${supporting.length>1?'push':'pushes'} the score ${yes?'up':'down'} from its baseline.`:'The model baseline and combined signals determine this result.');bars('contributions',items.filter(([,v])=>Math.abs(v)>1e-7).slice(0,5),Math.max(.01,...items.map(([,v])=>Math.abs(v))));$('baseline').textContent=`Baseline ${pct(result.base)} + all SHAP contributions = ${pct(result.probability)}. Blue lowers the score; lime raises it.`;$('path').replaceChildren(...result.path.map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));return result;}
 function setProfile(input){explain(model,input);for(const field of model.schema)controls[field.name].value=input[field.name];return render();}
 $('profile').addEventListener('submit',e=>{e.preventDefault();render();});$('profile').addEventListener('input',()=>{$('score-label').textContent='Profile changed · select Explain prediction to update';});$('reset').onclick=()=>setProfile(Object.fromEntries(model.schema.map(f=>[f.name,f.default])));
 for(const example of model.examples){const button=document.createElement('button');button.type='button';button.textContent=example.label;button.onclick=()=>setProfile(example.input);$('examples').append(button);}
 const m=model.metrics;for(const key of ['accuracy','precision','recall','f1']){const card=document.createElement('div');card.className='metric';const name=document.createElement('span');name.textContent=key==='f1'?'F1 score':key[0].toUpperCase()+key.slice(1);const value=document.createElement('strong');value.textContent=pct(m[key]);card.append(name,value);$('metrics').append(card);}
 $('split').textContent=`${m.test_rows.toLocaleString()} held-out records`;$('baseline-note').textContent=`Only ${pct(m.positive_rate)} of all customers subscribed. Always predicting “no” scores ${pct(m.baseline_accuracy)} accuracy on the test set, but finds no subscribers. Precision and recall use subscription as the positive class.`;
 $('matrix').innerHTML='<thead><tr><th scope="col">Actual ↓ / Predicted →</th><th scope="col">No</th><th scope="col">Yes</th></tr></thead><tbody>'+m.confusion_matrix.map((row,i)=>`<tr><th scope="row">${i?'Yes':'No'}</th>${row.map((v,j)=>`<td class="${i===j?'correct':''}">${v.toLocaleString()}</td>`).join('')}</tr>`).join('')+'</tbody>';
 bars('importance',model.importance);render();$('loading').hidden=true;$('app').hidden=false;
 if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{await document.modelContext.registerTool({name:'explain_customer',description:'Set the customer profile and display the decision tree prediction with SHAP contributions.',inputSchema:{type:'object',properties:Object.fromEntries(model.schema.map(f=>[f.name,f.options?{type:'string',enum:f.options}:{type:'integer',minimum:f.min,maximum:f.max}])),required:model.schema.map(f=>f.name),additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const r=setProfile(input);return {score:r.probability,contributions:r.contributions,path:r.path};}},{signal:lifecycle.signal});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch(e){console.warn('Optional browser tool unavailable',e);}}
}catch(error){$('loading').textContent='The model could not be loaded. Refresh the page or serve this folder over HTTP.';console.error(error);}
